esp-idf:
  cpu: 2
  mem: 4G
  disk: 15G
  image: focal
  cloud_init: ./cloud-config.yaml
  git_repos:
    - https://github.com/hdumcke/multipass-orchestrator-configurations.git
  build_scripts:
    - ./multipass-orchestrator-configurations/esp-idf/build.sh
