armctoolchain:
  cpu: 2
  mem: 2G
  disk: 5G
  image: jammy
  cloud_init: ./cloud-config.yaml
  git_repos:
    - https://github.com/hdumcke/multipass-orchestrator-configurations.git
    - https://github.com/weiminshen99/GD32-hover-master-slave.git
  build_scripts:
    - ./multipass-orchestrator-configurations/armctoolchain/build.sh
