arctoolchaim:
  cpu: 4
  mem: 2G
  disk: 15G
  image: jammy
  cloud_init: ./cloud-config.yaml
  git_repos:
    - https://github.com/hdumcke/multipass-orchestrator-configurations.git
    - https://github.com/hdumcke/linorobot2_hoverboard.git
  build_scripts:
    - ./multipass-orchestrator-configurations/arctoolchaim/build.sh
