mini-pupper-stanford:
  cpu: 2
  mem: 2G
  disk: 3G
  image: jammy
  cloud_init: ./cloud-config.yaml
  git_repo: https://github.com/hdumcke/mini_pupper_testig.git
  build_script: ./mini_pupper_testig/bsp_stanford_web_controller/setup_testing.sh
  run_script: ./StanfordQuadruped/tests/run_all_tests.sh
