mp-v2-esp-build:
  cpu: 2
  mem: 4G
  disk: 15G
  image: jammy
  cloud_init: ./cloud-config.yaml
  git_repos:
    - https://github.com/hdumcke/multipass-orchestrator-configurations.git
  build_scripts:
    - ./multipass-orchestrator-configurations/mp_v2_esp_build/build.sh
