mini-pupper-ros1:
  cpu: 2
  mem: 2G
  disk: 15G
  image: focal
  cloud_init: ./cloud-config.yaml
  git_repos:
    - https://github.com/hdumcke/mini_pupper_testig.git
  build_scripts:
    - ./mini_pupper_testig/v1_ros1_jupyter/setup_testing.sh
