otaserver:
  cpu: 2
  mem: 4G
  disk: 5G
  image: jammy
  cloud_init: ./cloud-config.yaml
  git_repos:
    - https://github.com/hdumcke/multipass-orchestrator-configurations.git
  build_scripts:
    - ./multipass-orchestrator-configurations/ota-server/build.sh
otaclient:
  cpu: 2
  mem: 4G
  disk: 5G
  image: jammy
  cloud_init: ./cloud-config.yaml
  git_repos:
    - https://github.com/hdumcke/multipass-orchestrator-configurations.git
  build_scripts:
    - ./multipass-orchestrator-configurations/ota-server/build_client.sh
